### ISSUE TITLE
Neo-tree integration

### ISSUE THREAD

**Issue by nscotto** [shortcuts/no-neck-pain.nvim#191]
## Describe the problem

When opening a file with neo-tree, it can open in the padding window.

## Describe the solution

I would like to be able to lock the padding window so that no file can open in it.

**Comment by shortcuts** [comment]
hey, thanks for opening the issue! We should indeed provide an integration for it, will definitely check this ASAP

**Comment by shortcuts** [comment]
hey there, it should now work as expected as per #192! enjoy and thanks for testing the plugin :D

**Comment by nscotto** [comment]
It works a lot better but still not perfectly though.
I get an error when I go from the scratchbuffer to neo-tree then from neo-tree I untoggle neo-tree.
Here's a preview:

https://user-images.githubusercontent.com/44670538/224643661-5e1fe4c8-a2d7-40ab-a0e2-75f1ccbbbbe1.mov

**Comment by shortcuts** [comment]
thanks for reopening! will investigate if there have been regressions introduced 🤔

**Comment by nscotto** [comment]
Another one that would improve the workflow with neo-tree (although it could be more on the neo-tree end), if I navigate back to neo-tree from the scratch buffer and open a file with neo-tree, neo-tree will open it in the last opened window and so this will take the place of the no-neck-pain scratch buffer:

https://user-images.githubusercontent.com/44670538/224653938-fb2e4393-a686-4e5f-af77-f819b3365abc.mov

**Comment by shortcuts** [comment]
> Another one that would improve the workflow with neo-tree (although it could be more on the neo-tree end), if I navigate back to neo-tree from the scratch buffer and open a file with neo-tree, neo-tree will open it in the last opened window and so this will take the place of the no-neck-pain scratch buffer:

Indeed it seems like a NeoTree issue instead, it's weird that it doesn't ask you in which buffer you'd like to open the file however 🤔

**Comment by shortcuts** [comment]
I've released the fix in https://github.com/shortcuts/no-neck-pain.nvim/releases/tag/v1.1.1, it should normally fix all kind of layout issue related to the side trees. Please don't hesitate to re-open if you have any doubt!
