### ISSUE TITLE
Neotree `close_if_last_window` does not work

### ISSUE THREAD

**Issue by sand4rt** [shortcuts/no-neck-pain.nvim#358]
## Steps to reproduce

1. open NNP
2. open neo-tree with `close_if_last_window = true`
3. close the window

## Expected behavior

Neovim should close, but it doesn't. It likely detects that NNP is still open, preventing it to close

## Environment

- Neovim version: 10
- no-neck-pain.nvim version: latest
- Plugin clash: neo-tree

**Comment by shortcuts** [comment]
Hey @sand4rt thanks for reporting the issue, would you mind describe the steps you've done to reproduce this? so far if I have the neo-tree open along with nnp and I `:q` on the centered buffer, it closes nvim properly

**Comment by shortcuts** [comment]
fix released here https://github.com/shortcuts/no-neck-pain.nvim/releases/tag/v1.14.0

**Comment by sand4rt** [comment]
Hi @shortcuts, just tested the latest release and the issue is still there:

https://github.com/shortcuts/no-neck-pain.nvim/assets/17591696/7cf43f70-38ae-43f2-a7b3-b5a32653097f

**Comment by shortcuts** [comment]
> Hi @shortcuts, just tested the latest release and the issue is still there:
> 
>  issue.mov 
> nvim should close at the end, but it doesn't. It's probably because neo-tree does not think it's the last window because NNP is open.

oh that's weird it's exactly what I tried, i'll write a test case for this to see if it behaves differently

**Comment by shortcuts** [comment]
Hey @sand4rt would you mind letting me know if those steps reproduce your issue on your side? https://github.com/shortcuts/no-neck-pain.nvim/pull/366

**Comment by sand4rt** [comment]
hi @shortcuts, thanks for your reply. Im not sure how to reproduce the steps in #366? This is what i did:

1. `:NoNeckPain` -- open NNP
2. `:Neotree` -- open Neotree
3. `<C-w><C-l>` -- Move focus to the main window
4. `:q` -- close nvim and make sure `close_if_last_window` is was to true in Neotree 
5.  neovim should be closed 

`close_if_last_window` in Neotree does work if NNP is not enabled btw.

**Comment by shortcuts** [comment]
> hi @shortcuts, thanks for your reply. Im not sure how to reproduce the steps in https://github.com/shortcuts/no-neck-pain.nvim/pull/366? This is what i did:

it looks like what I've executed in the test suite, I'll change it to match your input 1:1 and see how it behaves

**Comment by shortcuts** [comment]
https://github.com/shortcuts/no-neck-pain.nvim/assets/20689156/31d6eeab-32ab-4aff-bcc4-691a0a8bbbd5

Here's a screen recording with the configuration I've used at the end
