### ISSUE TITLE
neovim exits when current buffer is killed

### ISSUE THREAD

**Issue by bloznelis** [shortcuts/no-neck-pain.nvim#368]
Firstly, thank you for this plugin, I've been using it a lot!

## Description

If you have no-neck-pain enabled, and you kill an active buffer (e.g. using `:bd`) it exits neovim completely.

## Steps to reproduce

1. Load at least two buffers
2. `:NoNeckPain`
3. `:bd`
4. neovim exits

## Expected behavior

I would expect for it to show the other loaded buffer instead of exiting (like it does when no-neck-pain is not used).

## Environment

- Neovim version: `v0.10.0`
- no-neck-pain.nvim version: 1.14.0

**Comment by shortcuts** [comment]
Hey, thanks for using the plugin, glad you like it :)

You should not see the issue anymore after setting [fallbackOnBufferDelete = true](https://github.com/shortcuts/no-neck-pain.nvim/blob/main/lua/no-neck-pain/config.lua#L170), this will be defaulted to true in the next major version

**Comment by bloznelis** [comment]
Sorry for a late response,

I tried setting `fallbackOnBufferDelete = true`. Now it does not exit neovim, but opens a new empty buffer instead of any other loaded buffers. Maybe there is a setting to disable this too?

**Comment by lorentzforces** [comment]
Is this potentially related to #370 ?

**Comment by MikeSouto** [comment]
It is happening to me as well. 
nvim 0.10
no-neck-pain 1.14.1
using telescope 

Steps:
1. nvim in a directory
2. fzf to file
3. fzf to another file
4. <Leader>x to close the last buffer (vim.cmd.bw)

And it quit nvim

Anyway for your plugin, it is helping me a lot with my neck, but also to my eyes.

**Comment by bogdan-the-great** [comment]
For folks waiting for fix:

```
-- my keymap function for reference
local keymap = function(mode, lhs, rhs, desc)
	vim.keymap.set(mode, lhs, rhs, { noremap = true, silent = true, desc = desc })
end

...

keymap("n", "<S-x>", ":NoNeckPain<cr> :sleep 1m<cr> :bdelete<cr> :NoNeckPain<cr>", "")
```

Toggle NNP, sleep 1 milisecond, delete the buffer, toggle NNP back.

**Comment by shortcuts** [comment]
Hey there, sorry for the huge delay on the response, just got a baby few months ago, which takes as much time as tweaking my nvim config D:

I think the issue should be fixed with #375, if anyone has time, don't hesitate to confirm by testing on main :)

Thanks again for using the plugin!!

**Comment by bogdan-the-great** [comment]
Hi, this issue still persists for me in 1.16.1 with the default config.

The behavior is the same as said before:

> I tried setting `fallbackOnBufferDelete = true`. Now it does not exit neovim, but opens a new empty buffer instead of any other loaded buffers. Maybe there is a setting to disable this too?

Please ping me if you need testing.

**Comment by shortcuts** [comment]
Hey, I think I have a final fix for this on the `next` branch, in case you want to try it :)

(There should be no breaking changes)

**Comment by bogdan-the-great** [comment]
Okay, so it will work properly, but won't close Neovim when closing the last buffer. After testing with my config*, I narrowed it down to:
- `skipEnteringNoNeckPainBuffer = true` autocmd will close the current buffer and will send Neovim straight into purgatory, where it won't take any input (doesn't matter if it's the only option or among others),
- `fallbackOnBufferDelete` needs to be true, otherwise it will close Neovim (of course the `skipEnteringNoNeckPainBuffer` needs to be false or not present), but when true then it won't close Neovim when closing the last buffer.

<details>

<summary>*My config for 1.16.1 for reference</summary>

```
width = 100,
fallbackOnBufferDelete = false, -- because of my custom close behavior
buffers = {
    right = {
        enabled = false,
    },
    scratchPad = {
        -- set to `false` to disable auto-saving
        enabled = false,
        location = nil,
        -- set to `nil` to default to current working directory
    },
    bo = {
        filetype = "md",
    },
    wo = {
        fillchars = "eob: ",
    },
},
autocmds = {
    enableOnVimEnter = true,
    skipEnteringNoNeckPainBuffer = true,
},
```

</details>

Hope it helps!

**Comment by shortcuts** [comment]
thanks @bogdan-the-great !! indeed I also flagged a clash with [`skipEnteringNoNeckPainBuffer`](https://github.com/shortcuts/no-neck-pain.nvim/pull/384#issuecomment-2325324348), will resolve that too and we should be good :D

**Comment by shortcuts** [comment]
should be fixed on the last commit of `next`: https://github.com/shortcuts/no-neck-pain.nvim/pull/384/commits/db44bfdc44dc64a71aadc356adf21668caeb8bd8

**Comment by bogdan-the-great** [comment]
![image](https://github.com/user-attachments/assets/833ec05c-9164-4941-9bcb-5b61f8b4368e)

Now `skipEnteringNoNeckPainBuffer = true` doesn't hang Neovim, but the `fallbackOnBufferDelete` behaves the same way as before:

> `fallbackOnBufferDelete` needs to be true, otherwise it will close Neovim (of course the `skipEnteringNoNeckPainBuffer` needs to be false or not present), but when true then it won't close Neovim when closing the last buffer.

Tested with minimal config (only lazy.nvim and NNP).

**Comment by shortcuts** [comment]
Thanks for doing further testing @bogdan-the-great, would you mind describing which steps you are doing?

Here's what I'm trying out:

with `skipEnteringNoNeckPainBuffer` and `fallbackOnBufferDelete` to true:
1. open at least 2 buffers
2. open nnp
3. `:bd`
  - close the window, and the buffer focused
  - open a new window, with the other opened buffer in it

1. open only 1 buffer
2. open nnp
3. `:bd`
  - close the window, and the buffer focused
  - open a new window, with an empty buffer

without fallback, if there's only one window, quit nvim
