### ISSUE TITLE
bug: no-neck-pain buffer disappears when opening neo-tree

### ISSUE THREAD

**Issue by noahbald** [shortcuts/no-neck-pain.nvim#389]
## Description

Hey, haven't done an in-depth investigation on this one.
I recently updated NNP and it seems to have introduced this issue.

https://github.com/user-attachments/assets/c9e80609-eede-4bbd-88e0-5627e443a4c5

## Steps to reproduce

1. I did the command `require("neo-tree.command").execute({ toggle = true, dir = LazyVim.root() })`
2. Then I saw the left no-neck-pain buffer became non-visible
3. The cursor stayed within the original buffer, rather than neo-tree

## Expected behavior

1. I did the command `require("neo-tree.command").execute({ toggle = true, dir = LazyVim.root() })`
2. The no-neck-pain buffers adjust to be the same width
3. The cursor moves into neo-tree

## Environment

- Neovim version: [v0.10.1
- no-neck-pain.nvim version: 1109978 (latest)
- Plugin clash: neo-tree

**Comment by beetol** [comment]
I'm also have this same issue. Except when I want to reopen NNP, it doesn't open until I try it again a second time.

Another issue is that when NeoTree is open and then close, then reopen NNP, it gets resized narrowly.

My current solution is to open NeoTree in a float.

**Comment by maxguuse** [comment]
Same issue.

**Comment by shortcuts** [comment]
Hey there, really sorry for this issue! I went ahead with ba7475920e0de811768728589f6c1c7df156c803 but should've waited for https://github.com/shortcuts/no-neck-pain.nvim/pull/384 as it introduces a few bugs

I created a safe stable branch, without any issues, feel free to target it in the meantime of the major release https://github.com/shortcuts/no-neck-pain.nvim/tree/1.x, the appropriate GitHub tag is https://github.com/shortcuts/no-neck-pain.nvim/releases/tag/v1.14.1

------

Thanks for keeping up with the plugin though, I can confirm the issue, I'm working on a fix right now

**Comment by shortcuts** [comment]
Hey all, it should be fixed on the next branch https://github.com/shortcuts/no-neck-pain.nvim/pull/384/commits/6d76777f32c4c9defe944be27ce2d58e337ba4cd but if you don't mind trying it out maybe I missed some cases

**Comment by sand4rt** [comment]
Hi @shortcuts, thanks for the updates! I'm testing them out right now and i'm still experiencing this in v2.0.0

**Comment by gpwns3717** [comment]
Has no one experienced the width getting smaller after the Neo-tree toggle? Even after the v2.0.0 release, the problem has not been fixed.

https://github.com/user-attachments/assets/21e8c9dc-1d78-4171-9023-a7c323bdf6e2

**Comment by shortcuts** [comment]
Ohhhh I finally managed to reproduce, working on it!

**Comment by shortcuts** [comment]
I found the issue for the weird resizes/wrong computed width https://github.com/shortcuts/no-neck-pain.nvim/pull/391, however when closing the integration, the layout isn't properly restored yet, i'll check that tomrrow!

**Comment by shortcuts** [comment]
Hey there, sorry I had other stuff to work on but https://github.com/shortcuts/no-neck-pain.nvim/pull/391 should have integrations fixed now!

I'm not a proactive user of side trees, so if anyone can give it a try and give me feedbacks it would be gladly appreciated, thanks!

**Comment by beetol** [comment]
Works now! Now when NNP is toggled, open NeoTree, then close, the window is back to being centered.

Thank you!🚀

**Comment by shortcuts** [comment]
hugeeeee that's nice, thanks for testing it! I'll release the new version then :D
